fix(error): add a way to display error when job already running

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -58,8 +58,11 @@ runs:
       shell: bash
       name: read job id
       run: |
-	jobid=$(cat job.json | jq -rc '.job_id')
-	if [ -z "$jobid" ]; then exit 1; else exit 0; fi
+        status=$(cat job.json | jq -rc '.status')
+        error_message=$(cat job.json | jq -rc '.error')
+        if [[ "error" == $status ]]; then echo "error: $error_message"; exit 1; fi
+        jobid=$(cat job.json | jq -rc '.job_id')
+        if [ -z "$jobid" ]; then exit 1; else exit 0; fi
         keyval="job_id=$jobid"
         echo $keyval
         echo $keyval >> "$GITHUB_OUTPUT"
@@ -78,7 +81,8 @@ runs:
       shell: bash
       id: jobapi
       run: |
-        echo "status=$(cat job_status.json|jq -rc '.status ')" >> $GITHUB_ENV
+        echo $(cat job_status.json|jq -rc '.output')
+        echo "status=$(cat job_status.json|jq -rc '.status')" >> $GITHUB_ENV
 
     - name: Poll until it's okay
       if: env.status == 'starting'
